services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: horas-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      - SPRING_DATASOURCE_USERNAME=postgres.cdwyizubhattqgogpqen
      - SPRING_DATASOURCE_PASSWORD=Pyganflor.1996
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: horas-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
