spring.application.name=horas-app

# Configuración Base de Datos PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.cdwyizubhattqgogpqen}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pyganflor.1996}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del Servidor
server.port=8080

# Jackson (formato de fechas)
spring.jackson.serialization.write-dates-as-timestamps=false
